name: image_analysis
channels:
  - conda-forge
  - defaults
  - pytorch

 
dependencies:
  - cudatoolkit=10.1
  - h5py>=2.8
  - hdf5>=1.10
  - ipympl>=0.5
  - ipyparallel>=6.3
  - ipython>=7.18
  - jupyterlab>=2.2
  - matplotlib>=3.3
  - mkl>=2019.3
  - napari>=0.3.8
  - nodejs>=10.13
  - numba>=0.51
  - numpy>=1.19
  - opencv>=3.4
  - openjdk
  - pandas>=1.1
  - pip>=20.2
  - pylint>=2.6
  - pyqt>=5.9
  - python==3.8
  - pytorch
  - qt>=5.9
  - rope
  - scikit-image>=0.18
  - scikit-learn>=0.23
  - scipy>=1.5
  - tifffile>=2020.10
  - yaml>=0.2
  - zarr>=2.4
  - z5py>=2.0
  - pip:
    - fire>=0.3
    - pycziutils>=0.2.0
#    - mxnet-cu101mkl>=1.6.0
    - natsort>=7.1
    - pyqtgraph==0.11.0rc0
    - python-bioformats>=4.0
    - seaborn>=0.11
    - tables==3.5.1
    - termcolor>=1.1
    - tqdm>=4.54
    - xmltodict>=0.12         
    
#RUN conda config --add channels conda-forge
#RUN conda install -n cellpose pyimagej openjdk=8 
#RUN conda install -n cellpose pyjnius=1.2.0 #to avoid a bug https://github.com/imagej/pyimagej/issues/72
