name: shadow_correction_stitching
channels:
  - bioconda
  - defaults
  - omnia
  - conda-forge
dependencies:
  - dask
  - h5py
  - pip
  - yaml
  - zarr
  - numpy
  - scikit-image
  - aicsimageio
  
